[package]
name = "darwin-v7"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Unofficial rust client for the [V7 annotation platform](https://darwin.v7labs.com/)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
serde = "1.0"
serde_yaml = "0.9"

[dev-dependencies]
tempfile = "3.3"
